spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect


